name: Discord Bot 24/7
on:
  push:
    branches: [ main ]
  workflow_dispatch: # ไว้กดรันเองได้
  schedule:
    - cron: '0 */5 * * *' # สั่งให้รันอัตโนมัติทุกๆ 5 ชั่วโมง

jobs:
  run-bot:
    runs-on: ubuntu-latest
    # บังคับจบงานที่ 5 ชั่วโมง 50 นาที (350 นาที) จะได้ไม่ชนลิมิต 6 ชั่วโมงของ GitHub
    timeout-minutes: 350 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run Bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python main.py
